### ISSUE TITLE
Run ./run.sh 0 "A pineapple." but faild

### ISSUE THREAD

**Issue by emailandxu** [thu-ml/prolificdreamer#11]
File "/data1/git-repo/prolificdreamer/gridencoder/grid.py", line 54, in forward
    _backend.grid_encode_forward(inputs, embeddings, offsets, outputs, B, D, C, L, S, H, dy_dx, gridtype, align_corners, interpolation)
TypeError: grid_encode_forward(): incompatible function arguments. The following argument types are supported:
    1. (arg0: at::Tensor, arg1: at::Tensor, arg2: at::Tensor, arg3: at::Tensor, arg4: int, arg5: int, arg6: int, arg7: int, arg8: int, arg9: float, arg10: int, arg11: Optional[at::Tensor], arg12: int, arg13: bool, arg14: int) -> None

**Comment by r530044129** [comment]
im failed too, part of the failed log:
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
run.sh: line 17: $'\r': command not found
find: ‘exp-dmtet-stage2’: No such file or directory
run.sh: line 19: $'\r': command not found
Traceback (most recent call last):
  File "/mnt/d/git/prolificdreamer/main.py", line 5, in <module>
    from nerf.provider import NeRFDataset
  File "/mnt/d/git/prolificdreamer/nerf/provider.py", line 2, in <module>
    import cv2
  File "/home/allen/miniconda3/envs/proli/lib/python3.9/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/allen/miniconda3/envs/proli/lib/python3.9/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/home/allen/miniconda3/envs/proli/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

**Comment by emailandxu** [comment]
您的邮件我尽力在12小时内处理。I'll be responding within 12 hours.

**Comment by ByChelsea** [comment]
> File "/data1/git-repo/prolificdreamer/gridencoder/grid.py", line 54, in forward _backend.grid_encode_forward(inputs, embeddings, offsets, outputs, B, D, C, L, S, H, dy_dx, gridtype, align_corners, interpolation) TypeError: grid_encode_forward(): incompatible function arguments. The following argument types are supported: 1. (arg0: at::Tensor, arg1: at::Tensor, arg2: at::Tensor, arg3: at::Tensor, arg4: int, arg5: int, arg6: int, arg7: int, arg8: int, arg9: float, arg10: int, arg11: Optional[at::Tensor], arg12: int, arg13: bool, arg14: int) -> None

I've also encountered this issue, have you solved it?

I have solved it, you can refer to [this issue.](https://github.com/ashawkey/stable-dreamfusion/issues/108)

**Comment by emailandxu** [comment]
您的邮件我尽力在12小时内处理。I'll be responding within 12 hours.
